/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Html, useGLTF } from "@react-three/drei";
// import Pacman from "pacman-react";
import { Context, SnakeGame } from "react-game-snake";

export function Model(props) {
  const { nodes, materials } = useGLTF("/arcade.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[0.08, 0.02, 10.24]} rotation={[0, Math.PI / 2, 0]}>
        <group
          position={[0.12, 2.64, -2.71]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1, 1.05, 1]}
        >
          <mesh
            geometry={nodes.Plane011.geometry}
            material={materials["Material.023"]}
          />
          <mesh
            geometry={nodes.Plane011_1.geometry}
            material={materials["Material.024"]}
          />
          <mesh
            geometry={nodes.Plane011_2.geometry}
            material={materials["sCREEN.002"]}
          >
            <Html
              className="content"
              transform
              occlude
              rotation={[0, 1, 0]}
              // position={[1.07, 0.58, 0.1]}
              scale={0.2}
            >
              <div className="wrapper">
                <SnakeGame
                  colors={{
                    field: "#bdc3c7",
                    food: "#ff0000",
                    snake: "#3498db",
                  }}
                  countOfHorizontalFields={26}
                  countOfVerticalFields={30}
                  fieldSize={20}
                  loopTime={150}
                  pauseAllowed={true}
                  restartAllowed={false}
                  onLoose={(context) =>
                    console.log(`You Lost with ${context.game.points} points.`)
                  }
                  onPause={(context) => alert("paused")}
                  onRestart={(context) => alert("restarted")}
                  onResume={(context) => alert("onResume")}
                  onWin={(context) =>
                    console.log(`You won with ${context.game.points} points.`)
                  }
                />
              </div>
            </Html>
          </mesh>
          <mesh
            geometry={nodes.Plane011_3.geometry}
            material={materials["uPPER SCREEN.002"]}
          />
          <mesh
            geometry={nodes.Plane011_4.geometry}
            material={materials["Material.025"]}
          />
          <mesh
            geometry={nodes.Plane011_5.geometry}
            material={materials["Material.026"]}
          />
          <mesh
            geometry={nodes.Plane011_6.geometry}
            material={materials["Material.027"]}
          />
          <mesh
            geometry={nodes.Plane011_7.geometry}
            material={materials["Material.028"]}
          />
          <mesh
            geometry={nodes.Plane011_8.geometry}
            material={materials["Material.029"]}
          />
          <mesh
            geometry={nodes.Plane011_9.geometry}
            material={materials["Material.030"]}
          />
          <mesh
            geometry={nodes.Plane011_10.geometry}
            material={materials["Material.031"]}
          />
          <mesh
            geometry={nodes.Plane011_11.geometry}
            material={materials["Material.032"]}
          />
        </group>
        <group
          position={[3.46, 2.64, -2.71]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1, 1.05, 1]}
        >
          <mesh
            geometry={nodes.Plane012.geometry}
            material={materials["Material.033"]}
          />
          <mesh
            geometry={nodes.Plane012_1.geometry}
            material={materials["Material.034"]}
          />
          <mesh
            geometry={nodes.Plane012_2.geometry}
            material={materials["sCREEN.003"]}
          />
          <mesh
            geometry={nodes.Plane012_3.geometry}
            material={materials["uPPER SCREEN.003"]}
          />
          <mesh
            geometry={nodes.Plane012_4.geometry}
            material={materials["Material.035"]}
          />
          <mesh
            geometry={nodes.Plane012_5.geometry}
            material={materials["Material.036"]}
          />
          <mesh
            geometry={nodes.Plane012_6.geometry}
            material={materials["Material.037"]}
          />
          <mesh
            geometry={nodes.Plane012_7.geometry}
            material={materials["Material.038"]}
          />
          <mesh
            geometry={nodes.Plane012_8.geometry}
            material={materials["Material.039"]}
          />
          <mesh
            geometry={nodes.Plane012_9.geometry}
            material={materials["Material.040"]}
          />
          <mesh
            geometry={nodes.Plane012_10.geometry}
            material={materials["Material.041"]}
          />
          <mesh
            geometry={nodes.Plane012_11.geometry}
            material={materials["Material.042"]}
          />
        </group>
      </group>
      <group position={[10.35, 0.02, -0.04]} rotation={[0, -Math.PI / 2, 0]}>
        <group position={[-2.66, 2.64, 3.44]} scale={[1, 1.05, 1]}>
          <mesh
            geometry={nodes.Plane006_1.geometry}
            material={materials.Material}
          />
          <mesh
            geometry={nodes.Plane006_2.geometry}
            material={materials["Material.002"]}
          />
          <mesh
            geometry={nodes.Plane006_3.geometry}
            material={materials.sCREEN}
          />
          <mesh
            geometry={nodes.Plane006_4.geometry}
            material={materials["uPPER SCREEN"]}
          />
          <mesh
            geometry={nodes.Plane006_5.geometry}
            material={materials["Material.012"]}
          />
          <mesh
            geometry={nodes.Plane006_6.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            geometry={nodes.Plane006_7.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            geometry={nodes.Plane006_8.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            geometry={nodes.Plane006_9.geometry}
            material={materials["Material.008"]}
          />
          <mesh
            geometry={nodes.Plane006_10.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            geometry={nodes.Plane006_11.geometry}
            material={materials["Material.011"]}
          />
        </group>
        <group position={[-2.66, 2.64, 0.18]} scale={[1, 1.05, 1]}>
          <mesh
            geometry={nodes.Plane002_2.geometry}
            material={materials["Material.013"]}
          />
          <mesh
            geometry={nodes.Plane002_3.geometry}
            material={materials["Material.014"]}
          />
          <mesh
            geometry={nodes.Plane002_4.geometry}
            material={materials["sCREEN.001"]}
          />
          <mesh
            geometry={nodes.Plane002_5.geometry}
            material={materials["uPPER SCREEN.001"]}
          />
          <mesh
            geometry={nodes.Plane002_6.geometry}
            material={materials["Material.015"]}
          />
          <mesh
            geometry={nodes.Plane002_7.geometry}
            material={materials["Material.016"]}
          />
          <mesh
            geometry={nodes.Plane002_8.geometry}
            material={materials["Material.017"]}
          />
          <mesh
            geometry={nodes.Plane002_9.geometry}
            material={materials["Material.018"]}
          />
          <mesh
            geometry={nodes.Plane002_10.geometry}
            material={materials["Material.019"]}
          />
          <mesh
            geometry={nodes.Plane002_11.geometry}
            material={materials["Material.020"]}
          />
          <mesh
            geometry={nodes.Plane002_12.geometry}
            material={materials["Material.021"]}
          />
          <mesh
            geometry={nodes.Plane002_13.geometry}
            material={materials["Material.022"]}
          />
        </group>
      </group>
      <group scale={5}>
        <mesh
          geometry={nodes.Plane004_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Plane004_3.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials["Material.043"]}
        position={[-5, 7.32, -5]}
        scale={[2.61, 5, 2.61]}
      />
      <mesh
        geometry={nodes["577827227dd85860d2868448ab8fbd46"].geometry}
        material={materials["577827227dd85860d2868448ab8fbd46"]}
        position={[6.4, 7.09, -5]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={2.93}
      />
      <mesh
        geometry={nodes["577827227dd85860d2868448ab8fbd46001"].geometry}
        material={materials["577827227dd85860d2868448ab8fbd46.001"]}
        position={[0.92, 7.09, -5]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={2.93}
      />
      <mesh
        geometry={nodes["577827227dd85860d2868448ab8fbd46002"].geometry}
        material={materials["577827227dd85860d2868448ab8fbd46.002"]}
        position={[-5.01, 7.09, 0.48]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={2.93}
      />
      <mesh
        geometry={nodes["577827227dd85860d2868448ab8fbd46003"].geometry}
        material={materials["577827227dd85860d2868448ab8fbd46.003"]}
        position={[-5.01, 7.09, 6.09]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={2.93}
      />
      <group
        position={[0.12, 2.64, -2.71]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1, 1.05, 1]}
      >
        <mesh
          geometry={nodes.Plane011.geometry}
          material={materials["Material.023"]}
        />
        <mesh
          geometry={nodes.Plane011_1.geometry}
          material={materials["Material.024"]}
        />
        <mesh
          geometry={nodes.Plane011_2.geometry}
          material={materials["sCREEN.002"]}
        />
        <mesh
          geometry={nodes.Plane011_3.geometry}
          material={materials["uPPER SCREEN.002"]}
        />
        <mesh
          geometry={nodes.Plane011_4.geometry}
          material={materials["Material.025"]}
        />
        <mesh
          geometry={nodes.Plane011_5.geometry}
          material={materials["Material.026"]}
        />
        <mesh
          geometry={nodes.Plane011_6.geometry}
          material={materials["Material.027"]}
        />
        <mesh
          geometry={nodes.Plane011_7.geometry}
          material={materials["Material.028"]}
        />
        <mesh
          geometry={nodes.Plane011_8.geometry}
          material={materials["Material.029"]}
        />
        <mesh
          geometry={nodes.Plane011_9.geometry}
          material={materials["Material.030"]}
        />
        <mesh
          geometry={nodes.Plane011_10.geometry}
          material={materials["Material.031"]}
        />
        <mesh
          geometry={nodes.Plane011_11.geometry}
          material={materials["Material.032"]}
        />
      </group>
      <group
        position={[3.46, 2.64, -2.71]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1, 1.05, 1]}
      >
        <mesh
          geometry={nodes.Plane012.geometry}
          material={materials["Material.033"]}
        />
        <mesh
          geometry={nodes.Plane012_1.geometry}
          material={materials["Material.034"]}
        />
        <mesh
          geometry={nodes.Plane012_2.geometry}
          material={materials["sCREEN.003"]}
        />
        <mesh
          geometry={nodes.Plane012_3.geometry}
          material={materials["uPPER SCREEN.003"]}
        />
        <mesh
          geometry={nodes.Plane012_4.geometry}
          material={materials["Material.035"]}
        />
        <mesh
          geometry={nodes.Plane012_5.geometry}
          material={materials["Material.036"]}
        />
        <mesh
          geometry={nodes.Plane012_6.geometry}
          material={materials["Material.037"]}
        />
        <mesh
          geometry={nodes.Plane012_7.geometry}
          material={materials["Material.038"]}
        />
        <mesh
          geometry={nodes.Plane012_8.geometry}
          material={materials["Material.039"]}
        />
        <mesh
          geometry={nodes.Plane012_9.geometry}
          material={materials["Material.040"]}
        />
        <mesh
          geometry={nodes.Plane012_10.geometry}
          material={materials["Material.041"]}
        />
        <mesh
          geometry={nodes.Plane012_11.geometry}
          material={materials["Material.042"]}
        />
      </group>
      <group position={[-2.66, 2.64, 3.44]} scale={[1, 1.05, 1]}>
        <mesh
          geometry={nodes.Plane006_1.geometry}
          material={materials.Material}
        />
        <mesh
          geometry={nodes.Plane006_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Plane006_3.geometry}
          material={materials.sCREEN}
        />
        <mesh
          geometry={nodes.Plane006_4.geometry}
          material={materials["uPPER SCREEN"]}
        />
        <mesh
          geometry={nodes.Plane006_5.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          geometry={nodes.Plane006_6.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Plane006_7.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Plane006_8.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          geometry={nodes.Plane006_9.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          geometry={nodes.Plane006_10.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Plane006_11.geometry}
          material={materials["Material.011"]}
        />
      </group>
      <group position={[-2.66, 2.64, 0.18]} scale={[1, 1.05, 1]}>
        <mesh
          geometry={nodes.Plane002_2.geometry}
          material={materials["Material.013"]}
        />
        <mesh
          geometry={nodes.Plane002_3.geometry}
          material={materials["Material.014"]}
        />
        <mesh
          geometry={nodes.Plane002_4.geometry}
          material={materials["sCREEN.001"]}
        />
        <mesh
          geometry={nodes.Plane002_5.geometry}
          material={materials["uPPER SCREEN.001"]}
        />
        <mesh
          geometry={nodes.Plane002_6.geometry}
          material={materials["Material.015"]}
        />
        <mesh
          geometry={nodes.Plane002_7.geometry}
          material={materials["Material.016"]}
        />
        <mesh
          geometry={nodes.Plane002_8.geometry}
          material={materials["Material.017"]}
        />
        <mesh
          geometry={nodes.Plane002_9.geometry}
          material={materials["Material.018"]}
        />
        <mesh
          geometry={nodes.Plane002_10.geometry}
          material={materials["Material.019"]}
        />
        <mesh
          geometry={nodes.Plane002_11.geometry}
          material={materials["Material.020"]}
        />
        <mesh
          geometry={nodes.Plane002_12.geometry}
          material={materials["Material.021"]}
        />
        <mesh
          geometry={nodes.Plane002_13.geometry}
          material={materials["Material.022"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/arcade.glb");
